#!/bin/bash

VERSION=`cat configure.ac | grep AC_INIT | grep -Po [0-9]+\.[0-9]+\.[0-9]+`
DISTS="debian artful zesty yakkety xenial trusty"

for DIST in $DISTS; do
    ARGS=""
    CURRENT_VERSION=""

    if [ ! -f debian.$DIST/changelog ]; then
	ARGS="--create --package libcpuaff"
    else
        CURRENT_VERSION=`head -n1 debian.$DIST/changelog | grep -Po [0-9]+\.[0-9]+\.[0-9]+`
    fi

    if [ "$VERSION" = "$CURRENT_VERSION" ]; then
        VERSION_ARGS="-i"
    else
        VERSION_ARGS="-v $VERSION-1"
    fi

    dch $ARGS $VERSION_ARGS -c debian.$DIST/changelog -D $DIST $*
done
