title: cpuaff
email: dcdillon@gmail.com
baseurl: "/cpuaff"
url: ""

github_username: dcdillon
show_downloads: false
google_analytics:

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 5
paginate_path: "news/page:num/"